server:
  port: 8080

spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://rm-uf654i8ok1o971a07ro.mysql.rds.aliyuncs.com:3306/user-center?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      username: xuyuan
      password: xuyuan123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #配置元数据
        metadata:
          hello: world
          version: 0.1
#        namespace: 5a7fca12-1710-4fe9-8ce9-68329156cfdd
rocketmq:
  name-server: 47.115.60.46:9876
  producer:
    group: test-group
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
jwt:
  secret: aaaaaaaaaaaaabbbbbbbbbbbbbccccccccccccccccc
  expire-time-in-second: 1209600
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 1.0