server:
  port: 8877
spring:
  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        metadata:
#          instance: aa
#          namespace: 4eef7a74-a5bd-4ee2-b770-90b209d5417f
  datasource:
    url: jdbc:mysql://rm-uf654i8ok1o971a07ro.mysql.rds.aliyuncs.com:3306/user-center?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      username: xuyuan
      password: xuyuan123456
      driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

rocketmq:
  name-server: 101.200.130.236:9876
jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  expire-time-in-second: 1209600