server:
  port: 8888
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: 10e5a9a3-05ce-457f-b2a3-02bcfe1b512d
    sentinel:
      transport:
        dashboard: localhost:8080

  datasource:
    url: jdbc:mysql://rm-uf654i8ok1o971a07ro.mysql.rds.aliyuncs.com:3306/content-center?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      username: xuyuan
      password: xuyuan123456
      driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  expire-time-in-second: 1209600


user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  eager-load:
    enabled: true
    clients: user-center
logging:
  level:
    com.mqxu.contentcenter.feignclient.UserCenterFeignClient: debug
feign:
  client:
    config:
      user-center:
        loggerLevel: full
#feign:
#  client:
#    config:
#      # 全局配置
#      default:
#        loggerLevel: full
#  httpclient:
#    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
#    enabled: true
#    # feign的最大连接数
#    max-connections: 200
#    # feign单个路径的最大连接数

#    max-connections-per-route: 50

rocketmq:
  name-server: 101.200.130.236:9876
  producer:
    # 必须指定group
    group: test-group